//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardAccidentes.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardAccidentes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down1 {
            get {
                object obj = ResourceManager.GetObject("down1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eliminar_64 {
            get {
                object obj = ResourceManager.GetObject("eliminar_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap growth {
            get {
                object obj = ResourceManager.GetObject("growth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap growth_64 {
            get {
                object obj = ResourceManager.GetObject("growth_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_64 {
            get {
                object obj = ResourceManager.GetObject("map_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_64 {
            get {
                object obj = ResourceManager.GetObject("plus_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT {0}, l.latitud, l.longitud, COUNT(*) AS Accidentes
        ///FROM 
        ///(
        ///ACCIDENTE ac INNER JOIN 
        ///LOCALIZACION l ON ac.ID_Localizacion = l.ID_Localizacion INNER JOIN
        ///PROVINCIA p ON l.ID_Provincia = p.ID_Provincia INNER JOIN
        ///CANTON c ON l.ID_Canton = c.ID_Canton INNER JOIN 
        ///DISTRITO d ON l.ID_Distrito = d.ID_Distrito
        ///) 
        ///INNER JOIN
        ///(
        ///AFECTADO af INNER JOIN GENERO g ON af.ID_Sexo = g.ID_Sexo INNER JOIN
        ///LESION le ON af.ID_Lesion = le.ID_Lesion INNER JOIN
        ///ROLAFECTADO rol ON af.ID_Rol = rol.ID_Rol
        ///) 
        ///ON a [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string QUERY_DINAMICA_ESQUELETO {
            get {
                return ResourceManager.GetString("QUERY_DINAMICA_ESQUELETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT af.edad_quinquenal, ac.annio, COUNT(*) AS accidentes
        ///FROM	ACCIDENTE ac INNER JOIN
        ///		AFECTADO af ON ac.ID_Afectado = af.ID_Afectado
        ///GROUP BY af.edad_quinquenal, ac.annio
        ///ORDER BY af.edad_quinquenal, ac.annio;.
        /// </summary>
        internal static string QUERY_EDAD_QUINCENAL {
            get {
                return ResourceManager.GetString("QUERY_EDAD_QUINCENAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT g.sexo, ac.annio, COUNT(*) AS accidentes
        ///FROM	ACCIDENTE ac INNER JOIN
        ///		AFECTADO af ON ac.ID_Afectado = af.ID_Afectado INNER JOIN
        ///		GENERO g ON af.ID_Sexo = g.ID_Sexo
        ///GROUP BY g.sexo, ac.annio
        ///ORDER BY g.sexo, ac.annio;.
        /// </summary>
        internal static string QUERY_GENERO {
            get {
                return ResourceManager.GetString("QUERY_GENERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT rol.rol, COUNT(*) AS Accidentes
        ///FROM (ACCIDENTE ac INNER JOIN 
        ///		(AFECTADO af INNER JOIN ROLAFECTADO rol ON af.ID_Rol = rol.ID_Rol) 
        ///	 ON ac.ID_Afectado = af.ID_Afectado) INNER JOIN
        ///		(LOCALIZACION l INNER JOIN PROVINCIA p ON l.ID_Provincia = p.ID_Provincia)
        ///	 ON ac.ID_Localizacion = l.ID_Localizacion
        ///WHERE p.nombre_provincia = &apos;{0}&apos; AND ac.annio = {1}
        ///GROUP BY rol.rol;.
        /// </summary>
        internal static string QUERY_LIBRE {
            get {
                return ResourceManager.GetString("QUERY_LIBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT rol.rol, ac.annio, COUNT(*) AS accidentes
        ///FROM	ACCIDENTE ac INNER JOIN 
        ///		AFECTADO af ON ac.ID_Afectado = af.ID_Afectado INNER JOIN
        ///		ROLAFECTADO rol ON af.ID_Rol = rol.ID_Rol
        ///GROUP BY rol.rol, ac.annio
        ///ORDER BY rol.rol, ac.annio;.
        /// </summary>
        internal static string QUERY_ROL_AFECTADO {
            get {
                return ResourceManager.GetString("QUERY_ROL_AFECTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT l.tipo_lesion, ac.annio, COUNT(*) AS accidentes
        ///FROM	ACCIDENTE ac INNER JOIN
        ///		AFECTADO af ON ac.ID_Afectado = af.ID_Afectado INNER JOIN
        ///		LESION l ON af.ID_Lesion = l.ID_Lesion
        ///GROUP BY l.tipo_lesion, ac.annio
        ///ORDER BY l.tipo_lesion, ac.annio;.
        /// </summary>
        internal static string QUERY_TIPO_LESION {
            get {
                return ResourceManager.GetString("QUERY_TIPO_LESION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics {
            get {
                object obj = ResourceManager.GetObject("statistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics_64 {
            get {
                object obj = ResourceManager.GetObject("statistics_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up1 {
            get {
                object obj = ResourceManager.GetObject("up1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
